# -*- coding: utf-8 -*-
"""simulator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDVLxRKcTcY-S6TkHQ6ht6V-EROaWCND
"""

import time
import random
from dataclasses import dataclass
from typing import Dict, Any, Optional

# =========================================================
# Semiconductor Process Definition
# =========================================================

STEPS = [
    "DEPOSITION",
    "ETCH",
    "LITHOGRAPHY",
    "INSPECTION"
]

# =========================================================
# Equipment State
# =========================================================

@dataclass
class Equipment:
    equipment_id: str
    health_score: float = 1.0  # 1.0 = healthy

    def degrade(self):
        """장비 상태가 서서히 나빠짐"""
        self.health_score -= random.uniform(0.0001, 0.001)

        if self.health_score < 0.7:
            self.health_score = max(self.health_score, 0.5)

# =========================================================
# Wafer State Machine
# =========================================================

@dataclass
class Wafer:
    wafer_id: str
    lot_id: str
    step_index: int = 0

    def current_step(self):
        return STEPS[self.step_index]

    def next_step(self):
        self.step_index = (self.step_index + 1) % len(STEPS)

# =========================================================
# Semiconductor Simulator
# =========================================================

class SemiconductorSimulator:

    def __init__(
        self,
        wafer_count: int = 10,
        interval: float = 1.0
    ):
        self.wafer_count = wafer_count
        self.interval = interval

        self.wafers = self._create_wafers()
        self.equipments = self._create_equipments()

        self.running = False

    # -----------------------------------------------------

    def _create_wafers(self):
        return [
            Wafer(
                wafer_id=f"W{i:05}",
                lot_id=f"L{random.randint(1, 5):03}"
            )
            for i in range(self.wafer_count)
        ]

    def _create_equipments(self):
        equipments = {}

        for step in STEPS:
            equipments[step] = [
                Equipment(f"{step}-EQ-{i}")
                for i in range(1, 6)
            ]

        return equipments

    # -----------------------------------------------------

    def set_wafer_count(self, count: int):
        self.wafer_count = count
        self.wafers = self._create_wafers()

    def set_interval(self, interval: float):
        self.interval = interval

    # -----------------------------------------------------

    def _inject_missing_value(
        self,
        value: float,
        probability: float = 0.03
    ) -> Optional[float]:

        if random.random() < probability:
            return None

        return round(value, 4)

    # -----------------------------------------------------

    def _generate_process_metrics(
        self,
        step: str,
        equipment: Equipment
    ) -> Dict[str, Any]:

        health_factor = equipment.health_score

        # 장비 상태 나빠질수록 noise 증가
        noise = (1.0 - health_factor) * random.uniform(1, 10)

        if step == "DEPOSITION":

            metrics = {
                "temperature": random.uniform(60, 80) + noise,
                "pressure": random.uniform(0.9, 1.3),
                "gas_flow": random.uniform(30, 45),
                "rf_power": random.uniform(900, 1200),
                "humidity": random.uniform(30, 45),
            }

        elif step == "ETCH":

            metrics = {
                "temperature": random.uniform(70, 90) + noise,
                "pressure": random.uniform(0.7, 1.1),
                "gas_flow": random.uniform(40, 60),
                "rf_power": random.uniform(1100, 1500),
                "vibration": random.uniform(0.01, 0.05),
                "particle_count": random.randint(0, 20),
            }

        elif step == "LITHOGRAPHY":

            metrics = {
                "temperature": random.uniform(20, 25),
                "pressure": random.uniform(1.0, 1.1),
                "uv_intensity": random.uniform(700, 1000),
                "alignment_error": random.uniform(0.0, 0.03),
                "humidity": random.uniform(40, 50),
            }

        else:  # INSPECTION

            metrics = {
                "thickness_nm": random.uniform(90, 110),
                "defect_rate": random.uniform(0.0, 0.03),
                "particle_count": random.randint(0, 10),
                "surface_variance": random.uniform(0.0, 0.05),
            }

        # 결측치 추가 (SECOM 스타일)
        processed_metrics = {}

        for key, value in metrics.items():
            processed_metrics[key] = self._inject_missing_value(value)

        return processed_metrics

    # -----------------------------------------------------

    def _calculate_defect_probability(
        self,
        metrics: Dict[str, Any],
        equipment: Equipment
    ) -> float:

        probability = 0.001

        # 장비 상태 안좋으면 defect 증가
        probability += (1.0 - equipment.health_score) * 0.2

        # pressure 이상
        pressure = metrics.get("pressure")

        if pressure is not None:
            if pressure > 1.2 or pressure < 0.75:
                probability += 0.05

        # vibration 이상
        vibration = metrics.get("vibration")

        if vibration is not None:
            if vibration > 0.045:
                probability += 0.1

        # particle 많으면 defect 증가
        particles = metrics.get("particle_count")

        if particles is not None:
            if particles > 15:
                probability += 0.1

        return round(min(probability, 1.0), 4)

    # -----------------------------------------------------

    def generate_event(self, wafer: Wafer):

        step = wafer.current_step()

        equipment = random.choice(self.equipments[step])

        equipment.degrade()

        metrics = self._generate_process_metrics(
            step,
            equipment
        )

        defect_probability = self._calculate_defect_probability(
            metrics,
            equipment
        )

        event = {
            "timestamp": int(time.time()),

            "wafer_id": wafer.wafer_id,
            "lot_id": wafer.lot_id,

            "step": step,

            "equipment_id": equipment.equipment_id,
            "equipment_health": round(
                equipment.health_score,
                4
            ),

            **metrics,

            "defect_probability": defect_probability,

            # 실제 label
            "label": (
                "FAIL"
                if random.random() < defect_probability
                else "PASS"
            )
        }

        wafer.next_step()

        return event

    # -----------------------------------------------------

    def run(self):

        self.running = True

        while self.running:

            for wafer in self.wafers:

                event = self.generate_event(wafer)

                # TODO:
                # Kafka producer.send(...)
                print(event)

            time.sleep(self.interval)

    # -----------------------------------------------------

    def stop(self):
        self.running = False


# =========================================================
# Run
# =========================================================

if __name__ == "__main__":

    sim = SemiconductorSimulator(
        wafer_count=10,
        interval=1.0
    )

    sim.run()